EUAMVC/Models/Articles.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EUAMVC.Models
{
    public class Articles
    {
        public int Id { get; set; }
        public string ArticleName { get; set; }
        public string ArticleContext { get; set; }
        public string ArticleText { get; set; }
        public DateTime CreatedOn { get; set; }
        public bool ImportantNews { get; set; }

    }
}

EUAMVC/Models/CreateArticles.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EUAMVC.Models
{
    public class CreateArticles
    {
        public string ArticleName { get; set; }
        public string ArticleContext { get; set; }
        public string ArticleText { get; set; }
        public DateTime CreatedOn { get; set; }
        public bool ImportantNews { get; set; }
    }
}

EUAMVC/Models/ErrorViewModel.cs
using System;

namespace EUAMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EUAMVC/Models/EuaDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EUAMVC.Models
{
    public class EuaDbContext :DbContext
    {
        public EuaDbContext(DbContextOptions<EuaDbContext> options) : base(options) {

        }
    public DbSet<Articles> Articles { get; set; }
        public DbSet<Articles> CreateArticles { get; set; }
        public DbSet<Streams> Streams { get; set; }
    }
    }

 

EUAMVC/Models/IndexArticles.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EUAMVC.Models
{
    public class IndexArticles
    {
        public List<Articles> importantViewModel { get; set; }
        public List<Articles> unimportantViewModel { get; set; }
    }
}

EUAMVC/Models/StreamList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EUAMVC.Models
{
    public class StreamList
    {
        public List<Streams> StreamHistory { get; set; }
    }
}

EUAMVC/Models/Streams.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EUAMVC.Models
{
    public class Streams
    {
        public int Id { get; set; }
        public string StreamHeader { get; set; }
        public string StreamLink { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}

EUAMVC/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EUAMVC.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EUAMVC.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly EuaDbContext _db;
        public ArticlesController(EuaDbContext db)
        {
            _db = db;
        }
        public IActionResult Articles(int id)
        {
           
            Articles Article = _db.Articles.Single(art => art.Id == id);
            return View(Article);
        }
        public IActionResult CreateArticles()
        {

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateArticles(
    [Bind("Id,ArticleName,ArticleText,ArticleContext,ImportantNews,CreatedOn")] Articles article)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Articles.Add(article);
                    _db.SaveChanges();
                    return RedirectToAction(nameof(Streams));
                }
            }
            catch (Exception /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            return View(article);
        }
    }
}

EUAMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EUAMVC.Models;

namespace EUAMVC.Controllers
{
    public class HomeController : Controller
    {

        private readonly EuaDbContext _db;
        public HomeController(EuaDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(int page =0)
        {
             const int PageSize = 4;
            var count = _db.Articles.Count();

            IndexArticles viewmodel = new IndexArticles();
            viewmodel.importantViewModel = _db.Articles.OrderByDescending(o => o.Id).Where(o => o.ImportantNews == true).ToList();
            viewmodel.unimportantViewModel = _db.Articles.OrderByDescending(o => o.Id).Where(o => o.ImportantNews == false).Skip(page * PageSize).Take(PageSize).ToList();
            this.ViewBag.MaxPage = (count / PageSize) - (count % PageSize == 0 ? 1 : 0);
            this.ViewBag.Page = page;

            return View(viewmodel);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EUAMVC/Controllers/StreamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EUAMVC.Models;
using PagedList.Core;// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EUAMVC.Controllers
{
    public class StreamController : Controller
    {
        private readonly EuaDbContext _db;
        public StreamController(EuaDbContext db)
        {
            _db = db;
        }
     
        public IActionResult Stream(int page = 0)
        {
            const int PageSize = 2;
            var count = _db.Streams.Count();

            StreamList viewmodel = new StreamList();
            viewmodel.StreamHistory = _db.Streams.OrderByDescending(o => o.Id).Skip(page * PageSize).Take(PageSize).ToList();
            this.ViewBag.MaxPage = (count / PageSize) - (count % PageSize == 0 ? 1 : 0);
            this.ViewBag.Page = page;

            return View(viewmodel);
        }
    }
}
 

EUAMVC/Views/Articles/Articles.cshtml
@model EUAMVC.Models.Articles
@{
    ViewBag.Title = "Articles";

}
<div class="article">
    <dl>
        <dd>
            <h1>

                @Html.Raw(System.Web.HttpUtility.HtmlDecode(Model.ArticleName))
            </h1>
        </dd>

        <dd>
            <p>

                @Html.Raw(System.Web.HttpUtility.HtmlDecode(Model.ArticleText))
            </p>
            <p>
                @Html.DisplayFor(model => model.CreatedOn)
            </p>
        </dd>


    </dl>

</div>

EUAMVC/Views/Articles/CreateArticles.cshtml
@model EUAMVC.Models.Articles
@{
    ViewBag.Title = "Create Articles";

}

<text>
Articl name:<input type="text" name="Article Name" />
    Articl name:<input type="text" name="Article Context" />
    Articl name:<input type="text" name="Article Text" />
    <input type="submit" value="Submit" />
</text>
@using (Html.BeginForm()){
@Html.AntiForgeryToken()
    <div>
        @Html.LabelFor(model => model.ArticleName)
        @Html.EditorFor(model => model.ArticleName)
    </div>
    <div>
        @Html.LabelFor(model => model.ArticleContext)
        @Html.EditorFor(model => model.ArticleContext)
    </div>

    <div>
        @Html.LabelFor(model => model.ArticleText)
        @Html.EditorFor(model => model.ArticleText)
    </div>

    <div>
        @Html.LabelFor(model => model.ImportantNews)
        @Html.EditorFor(model => model.ImportantNews)
    </div>
    <div>
        @Html.LabelFor(model => model.CreatedOn)
        @Html.EditorFor(model => model.CreatedOn)
    </div>
    <div>
        <input type="submit" value="Create"/>
    </div>

}

EUAMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

EUAMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EUAMVC/Views/Home/Index.cshtml
@using EUAMVC.Models
@model IndexArticles

<div id="newsMenu">
    @{ int i = 0;}

    @{  var items = Model.importantViewModel;   }
    <a href="@Url.Action("Articles","Articles",new {id=items[i].Id})">
        <div class="rowTopLeft">
            <h1>
                @Html.DisplayFor(modelItem => items[i].ArticleName)
            </h1>
            <p>@Html.DisplayFor(modelItem => items[i].ArticleContext)</p>
            <p style="float:right;     font-size: calc(2px + 0.9vw);">@Html.DisplayFor(modelItem => items[i].CreatedOn)</p>

            @{i++;}
        </div>
    </a>
    <a href="@Url.Action("Articles","Articles",new {id=items[i].Id})">
        <div class="rowTopRight">

            <h1>
                @Html.DisplayFor(modelItem => items[i].ArticleName)
            </h1>
            <p>@Html.DisplayFor(modelItem => items[i].ArticleContext)</p>
            <p style="float:right;     font-size: calc(2px + 0.9vw);">@Html.DisplayFor(modelItem => items[i].CreatedOn)</p>

            @{i++;}
        </div>
    </a>
    <a href="@Url.Action("Articles", "Articles", new {id=items[i].Id})">
        <div class="rowBottomRight">
            <h1>
                @Html.DisplayFor(modelItem => items[i].ArticleName)
            </h1>
            <p>@Html.DisplayFor(modelItem => items[i].ArticleContext)</p>
            <p style="float:right;     font-size: calc(2px + 0.9vw);">@Html.DisplayFor(modelItem => items[i].CreatedOn)</p>
            @{i++;}
        </div>
    </a>
    <a href="@Url.Action("Articles","Articles",new {id=items[i].Id})">
        <div class="rowBottomLeft">
            <h1>
                @Html.DisplayFor(modelItem => items[i].ArticleName)
            </h1>
            <p>@Html.DisplayFor(modelItem => items[i].ArticleContext)</p>
            <p style="float:right;     font-size: calc(2px + 0.9vw);">@Html.DisplayFor(modelItem => items[i].CreatedOn)</p>
            @{i++;}
        </div>
    </a>



</div>
<div class="otherNews">
    @for (int x = 0; x < Model.unimportantViewModel.Count; x++)
    {
        <ul>
            <a href="@Url.Action("Articles","Articles",new {id=Model.unimportantViewModel[x].Id})">

                <h1> @Html.DisplayFor(modelItem => modelItem.unimportantViewModel[x].ArticleName)</h1>
                <p> @Html.DisplayFor(modelItem => modelItem.unimportantViewModel[x].ArticleContext)</p>
            </a>
        </ul>
    }

    <span>
        @if (ViewBag.Page > 0)
        {
            <a href="@Url.Action("Index", new { page = ViewBag.Page - 1 })"
               class="btn btn-default">
                &laquo; Iepriekšējā
            </a>
        }
    </span>
    <span>
        @if (ViewBag.Page < ViewBag.MaxPage - 1)
        {
            <a href="@Url.Action("Index", new { page = ViewBag.Page + 1 })"
               class="btn btn-default">
                Nākamā &raquo;
            </a>
        }
    </span>

</div>

EUAMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EUA2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/Default.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="header"></div>
    <div class="navibar">
        <ul>
            <li>@Html.ActionLink("Sākums", "Index", "Home")</li>
            <li>@Html.ActionLink("Spēles", "Games", "Home")</li>
            <li>@Html.ActionLink("Straume", "Stream", "Stream")</li>
            <li>@Html.ActionLink("Kontakti", "Contact", "Home")</li>
            <li>@Html.ActionLink("Par mani", "About", "Home")</li>
            <li>@Html.ActionLink("Raksti", "CreateArticles", "Articles")</li>
            <li>@Html.ActionLink("Raksti", "Articles", "Articles")</li>

        </ul>

    </div>

    <div class="container body-content">
        @RenderBody()
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

EUAMVC/Views/Stream/Stream.cshtml
@using EUAMVC.Models
@model StreamList
@{
    ViewBag.Title = "Articles";

}

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<div class="stream">
    @for (int x = 0; x < Model.StreamHistory.Count; x++)
    {
        <ul>
           

                <h1> @Html.DisplayFor(modelItem => modelItem.StreamHistory[x].StreamHeader)</h1>
            <iframe width="600" height="345" src=@Html.DisplayFor(modelItem => modelItem.StreamHistory[x].StreamLink)></iframe>
            
        </ul>
    }
</div>
<div class="otherNews">
    <span>
        @if (ViewBag.Page > 0)
        {
            <a href="@Url.Action("Stream", new { page = ViewBag.Page - 1 })"
               class="btn btn-default">
                &laquo; Iepriekšējā
            </a>
        }
    </span>
    <span>
        @if (ViewBag.Page < ViewBag.MaxPage - 1)
        {
            <a href="@Url.Action("Stream", new { page = ViewBag.Page + 1 })"
               class="btn btn-default">
                Nākamā &raquo;
            </a>
        }
    </span>
    </div>